version: "3.8"
services:
  livewier_app:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
    hostname: livewier_app
    labels:
      app: livewire_app
    container_name: livewire_app
    image: livewire_app:latest
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    networks:
      - travellist
      - db
  nginx:
    image: nginx:1.17-alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - travellist
      - db

networks:
  travellist:
  db:
    external: true